package it.ugolandini.drools.rules;

import it.ugolandini.drools.model.Customer
import it.ugolandini.drools.model.Customer.Category

rule "Silver customer rule"
  when
    $c: Customer(age>50)
  then
    $c.setCategory(Category.SILVER);
    System.out.println($c.toString() + " is a Silver customer");
end

rule "Platinum customer rule"
when
    $c: Customer(age>18, name == "ugo")
  then
    $c.setCategory(Category.PLATINUM);
    System.out.println($c.toString() + " is a Platinum customer");
end